// Korean to English LEGO search keyword dictionary
// Sorted by priority: exact phrases first, then single words

var SET_NUM_MAP = {
  '용마성': '6082',
  '비룡성': '6086',
  '흡룡성': '6085',
  '박쥐성': '6097',
  '유령성': '6081',
  '사자성': '6080',
  '왕의성': '6080',
  '숙의성': '6077',
  '숨의성': '6077',
  '숨속성': '6077',
  '숨속요새': '6077',
  '흡기사성': '6086',
  '마차성': '6042',
  '마법사성': '6048',
  '마법성': '6048',
  '독수리성': '6098',
  '사자기사성': '10305',
  '황소성': '375',
  '노란성': '375',
  '블랙펄': '10365',
  '블랙 펄': '10365',
  '해적선': '10365',
  '잭스패로우': '10365',
  '잭 스패로우': '10365',
  '쳨리비안의해적': '10365',
  '쳨리비안 해적': '10365',
  // ===== Pirates of Barracuda Bay (21322) =====
  '바라쿠다': '21322',
  '바라쿠다베이': '21322',
  '바라쿠다 베이': '21322',
  '바라쿠다베이의해적': '21322',
  '바라쿠다 베이의 해적': '21322',
  '바라쿠다베이해적': '21322',
  '바라쿠다 베이 해적': '21322',
  '바라쿠다섬': '21322',
  '바라쿠다 섬': '21322',
  '아이디어해적선': '21322',
  '아이디어 해적선': '21322',
  '타이타닉': '10294',
  '콜로세움': '10276',
  '에펄탑': '10307',
  '나무집': '21318',
  '트리하우스': '21318',
  '중세대장간': '21325',
  '중세 대장간': '21325',
  '그랜드피아노': '21323',
  '지구본': '21332',
  '타자기': '21327',
  '콘코드': '10318',
  '밀레니엄팜콘': '75192',
  '밀레니엄 팜콘': '75192',
  '디즈니성': '71040',
  '디즈니 성': '71040',
  '디즈니커슬': '71040',
  // ===== Modular Buildings =====
  '카페코너': '10182',
  '카페 코너': '10182',
  '그린그로서': '10185',
  '그린 그로서': '10185',
  '야채가게': '10185',
  '마켓스트리트': '10190',
  '마켓 스트리트': '10190',
  '소방대': '10197',
  '국민모듈러': '10197',
  '대형백화점': '10211',
  '그랜드엠포리엄': '10211',
  '그랜드 엠포리엄': '10211',
  '백화점': '10211',
  '펫샵': '10218',
  '펫 샵': '10218',
  '애완동물샵': '10218',
  '애완동물 가게': '10218',
  '타운홀': '10224',
  '타운 홀': '10224',
  '시청': '10224',
  '팔레스시네마': '10232',
  '팔레스 시네마': '10232',
  '파리지앵레스토랑': '10243',
  '파리지앵 레스토랑': '10243',
  '파리 레스토랑': '10243',
  '파리의 레스토랑': '10243',
  '탐정사무소': '10246',
  '탐정 사무소': '10246',
  '브릭뭅크': '10251',
  '브릭 뭅크': '10251',
  '브릭은행': '10251',
  '어셈블리스퀘어': '10255',
  '어셈블리 스퀘어': '10255',
  '다운타운다이너': '10260',
  '다운타운 다이너': '10260',
  '코너가라지': '10264',
  '코너 가라지': '10264',
  '코너정비소': '10264',
  '코너 정비소': '10264',
  '서점': '10270',
  '북샵': '10270',
  '북 샵': '10270',
  '모듈러경찰서': '10278',
  '모듈러 경찰서': '10278',
  '부티크호텔': '10297',
  '부티크 호텔': '10297',
  '재즈클럽': '10312',
  '재즈 클럽': '10312',
  '자연사박물관': '10326',
  '자연사 박물관': '10326',
  '튜더코너': '10350',
  '튜더 코너': '10350',
  '쇼핑스트리트': '11371',
  '쇼핑 스트리트': '11371',
};

var PHRASE_MAP = [
  // ===== Harry Potter =====
  ['다이애랩건 알리', 'Diagon Alley'],
  ['다이애랩건알리', 'Diagon Alley'],
  ['해리포터', 'Harry Potter'],
  ['해리 포터', 'Harry Potter'],
  ['호그와트 익스프레스', 'Hogwarts Express'],
  ['호그와트 성', 'Hogwarts Castle'],
  ['호그와트성', 'Hogwarts Castle'],
  ['호그와트리링', 'Hogsmeade'],
  ['호그마리', 'Hogsmeade'],
  ['따른내냨', 'Diagon Alley'],
  ['내냨거리', 'Diagon Alley'],
  ['호그낸른', 'Hogsmeade'],

  // ===== Pirates =====
  ['비나칭', 'Pirates'],
  ['비나칭내외', 'Pirates'],
  ['블랙 펄', 'Black Pearl'],
  ['쳨리비안의 해적', 'Pirates of the Caribbean'],
  ['쳨리비안 해적', 'Pirates of the Caribbean'],
  ['잭스패로우', 'Jack Sparrow'],
  ['잭 스패로우', 'Jack Sparrow'],
  ['쳪턴 잭 스패로우', 'Captain Jack Sparrow'],
  ['바라쿠다 베이', 'Barracuda Bay'],
  ['바라쿠다베이', 'Barracuda Bay'],
  ['바라쿠다 베이의 해적', 'Pirates of Barracuda Bay'],
  ['바라쿠다베이의 해적', 'Pirates of Barracuda Bay'],

  // ===== Modular Buildings =====
  ['카페코너', 'Cafe Corner'],
  ['카페 코너', 'Cafe Corner'],
  ['그린그로서', 'Green Grocer'],
  ['그린 그로서', 'Green Grocer'],
  ['마켓스트리트', 'Market Street'],
  ['마켓 스트리트', 'Market Street'],
  ['소방대', 'Fire Brigade'],
  ['국민모듈러', 'Fire Brigade'],
  ['대형백화점', 'Grand Emporium'],
  ['그랜드엠포리엄', 'Grand Emporium'],
  ['그랜드 엠포리엄', 'Grand Emporium'],
  ['펫샵', 'Pet Shop'],
  ['펫 샵', 'Pet Shop'],
  ['애완동물샵', 'Pet Shop'],
  ['애완동물 가게', 'Pet Shop'],
  ['팔레스시네마', 'Palace Cinema'],
  ['팔레스 시네마', 'Palace Cinema'],
  ['파리지앵레스토랑', 'Parisian Restaurant'],
  ['파리지앵 레스토랑', 'Parisian Restaurant'],
  ['파리 레스토랑', 'Parisian Restaurant'],
  ['파리의 레스토랑', 'Parisian Restaurant'],
  ['탐정사무소', "Detective's Office"],
  ['탐정 사무소', "Detective's Office"],
  ['브릭뭅크', 'Brick Bank'],
  ['브릭 뭅크', 'Brick Bank'],
  ['브릭은행', 'Brick Bank'],
  ['코너정비소', 'Corner Garage'],
  ['코너 정비소', 'Corner Garage'],
  ['북샵', 'Bookshop'],
  ['북 샵', 'Bookshop'],
  ['모듈러경찰서', 'Police Station'],
  ['모듈러 경찰서', 'Police Station'],
  ['튜더코너', 'Tudor Corner'],
  ['튜더 코너', 'Tudor Corner'],
  ['쇼핑스트리트', 'Shopping Street'],
  ['쇼핑 스트리트', 'Shopping Street'],

  // ===== Technic vehicles =====
  ['뎘이던동차', 'Motorized RC Car'],
  ['뎘이던 동차', 'Motorized RC Car'],
  ['거대온뫐네더', 'Geared RC Car'],
  ['거대 온뫐네더', 'Geared RC Car'],

  // ===== Multi-word phrases =====
  ['캡틴 아메리카', 'Captain America'],
  ['블랙 위도우', 'Black Widow'],
  ['블랙 팬서', 'Black Panther'],
  ['닥터 스트레인지', 'Doctor Strange'],
  ['인피니티 건틀렛', 'Infinity Gauntlet'],
  ['원더 우먼', 'Wonder Woman'],
  ['베이비 요다', 'Grogu'],
  ['다스 베이더', 'Darth Vader'],
  ['루크 스카이워커', 'Luke Skywalker'],
  ['한 솔로', 'Han Solo'],
  ['카일로 렌', 'Kylo Ren'],
  ['클론 트루퍼', 'Clone Trooper'],
  ['밀레니엄 팔콘', 'Millennium Falcon'],
  ['타이 파이터', 'TIE Fighter'],
  ['엑스 윙', 'X-Wing'],
  ['데스 스타', 'Death Star'],
  ['스타 데스트로이어', 'Star Destroyer'],
  ['해리 포터', 'Harry Potter'],
  ['반지의 제왕', 'Lord of the Rings'],
  ['인디아나 존스', 'Indiana Jones'],
  ['쥬라기 월드', 'Jurassic World'],
  ['쥬라기 공원', 'Jurassic Park'],
  ['스트레인저 씽스', 'Stranger Things'],
  ['미키 마우스', 'Mickey Mouse'],
  ['라이온 킹', 'Lion King'],
  ['토이 스토리', 'Toy Story'],
  ['슈퍼 마리오', 'Super Mario'],
  ['스피드 챔피언', 'Speed Champions'],
  ['미니 쿠퍼', 'Mini Cooper'],
  ['캠핑 카', 'Camper Van'],
  ['크리스마스 트리', 'Christmas Tree'],

  // ===== Multi-word phrases (added 2026-04-07 batch 2) =====
  ['아캄 어사일럼', 'Arkham Asylum'],
  ['배트 케이브', 'Batcave'],
  ['해리 퀸', 'Harley Quinn'],
  ['미스터 프리즈', 'Mr. Freeze'],
  ['투 페이스', 'Two-Face'],
  ['그린 고블린', 'Green Goblin'],
  ['닥터 옥토퍼스', 'Doctor Octopus'],
  ['스파이더 그웬', 'Spider-Gwen'],
  ['마일즈 모랄레스', 'Miles Morales'],
  ['닉 퓨리', 'Nick Fury'],
  ['캡틴 마블', 'Captain Marvel'],
  ['보바 펫', 'Boba Fett'],
  ['장고 펫', 'Jango Fett'],
  ['포 다메론', 'Poe Dameron'],
  ['카운트 두쿠', 'Count Dooku'],
  ['콰이곤 진', 'Qui-Gon Jinn'],
  ['메이스 윈두', 'Mace Windu'],
  ['오비완 케노비', 'Obi-Wan Kenobi'],
  ['신비한 동물사전', 'Fantastic Beasts'],
  ['미녀와 야수', 'Beauty and the Beast'],
  ['몬스터 주식회사', 'Monsters Inc'],
  ['니모를 찾아서', 'Finding Nemo'],
  ['인사이드 아웃', 'Inside Out'],
  ['빅 히어로', 'Big Hero'],
  ['닌자 거북이', 'Ninja Turtles'],
  ['반지 원정대', 'Fellowship of the Ring'],
  ['두 개의 탑', 'Two Towers'],
  ['왕의 귀환', 'Return of the King'],
  ['우주 비행사', 'Astronaut'],
  ['우주 정거장', 'Space Station'],
  ['스페이스 셔틀', 'Space Shuttle'],
];

var WORD_MAP = {
  '다이애랩건': 'Diagon Alley',
  '나무': 'Tree',
  '모듈러': 'Modular',
  '스타워즈': 'Star Wars',
  '스타': 'Star',
  '마법': 'Magic',
  '성': 'Castle',
  '해적': 'Pirate',
  '바라쿠다': 'Barracuda',
  '바라쿠다베이': 'Barracuda Bay',
  '우주': 'Space',
  '도시': 'City',
  '기차': 'Train',
  '비행기': 'Airplane',
  '로봇': 'Robot',
  '닌자고': 'Ninjago',
  '테크닉': 'Technic',
  '듀플로': 'Duplo',
  '프렌즈': 'Friends',
  '배트맨': 'Batman',
  '슈퍼히어로': 'Super Hero',
  '마인크래프트': 'Minecraft',
  '마인 크래프트': 'Minecraft',
  '아이디어': 'Ideas',
  '크리에이터': 'Creator',
  '크리에이터 전문가': 'Creator Expert',
  '아키텍처': 'Architecture',
  // ===== Common Korean search terms =====
  '경찰서': 'Police Station',
  '경찰': 'Police',
  '소방서': 'Fire Station',
  '소방': 'Fire',
  '병원': 'Hospital',
  '학교': 'School',
  '공항': 'Airport',
  '항구': 'Harbor',
  '항구도시': 'Harbor City',
  '배': 'Ship',
  '배배': 'Ship',
  '비행': 'Flight',
  '소방차': 'Fire Truck',
  '경찰차': 'Police Car',
  '자동차': 'Car',
  '트럭': 'Truck',
  '버스': 'Bus',
  '헬리콥터': 'Helicopter',
  '오토바이': 'Motorcycle',
  '농장': 'Farm',
  '정글': 'Jungle',
  '탐험': 'Exploration',
  '우주선': 'Spaceship',
  '로켓': 'Rocket',
  '달기지': 'Moon Base',
  '화성': 'Mars',
  '공룡': 'Dinosaur',
  '연립': 'United',
  '박물관': 'Museum',
  '도서관': 'Library',
  '식당': 'Restaurant',
  '카페': 'Cafe',
  '호텔': 'Hotel',
  '영화관': 'Cinema',
  '가게': 'Shop',
  '상점': 'Store',
  '시장': 'Market',
  '레스토랑': 'Restaurant',
  '은행': 'Bank',
  '우체국': 'Post Office',
  '주유소': 'Gas Station',
  '정비소': 'Garage',
  // ===== Marvel / DC / Star Wars / Movies / IPs / Brands / Botanical (added 2026-04) =====
  '마블': 'Marvel',
  '어벤져스': 'Avengers',
  '어벤저스': 'Avengers',
  '스파이더맨': 'Spider-Man',
  '아이언맨': 'Iron Man',
  '캡틴아메리카': 'Captain America',
  '토르': 'Thor',
  '헐크': 'Hulk',
  '블랙위도우': 'Black Widow',
  '블랙팬서': 'Black Panther',
  '가디언즈': 'Guardians of the Galaxy',
  '가디언즈오브갤럭시': 'Guardians of the Galaxy',
  '닥터스트레인지': 'Doctor Strange',
  '앤트맨': 'Ant-Man',
  '완다': 'Wanda',
  '로키': 'Loki',
  '타노스': 'Thanos',
  '인피니티건틀렛': 'Infinity Gauntlet',
  '헐크버스터': 'Hulkbuster',
  '디씨': 'DC',
  '슈퍼맨': 'Superman',
  '원더우먼': 'Wonder Woman',
  '아쿠아맨': 'Aquaman',
  '플래시': 'Flash',
  '조커': 'Joker',
  '배트모빌': 'Batmobile',
  '만달로리안': 'Mandalorian',
  '만달로어': 'Mandalorian',
  '베이비요다': 'Grogu',
  '그로구': 'Grogu',
  '다스베이더': 'Darth Vader',
  '요다': 'Yoda',
  '루크스카이워커': 'Luke Skywalker',
  '한솔로': 'Han Solo',
  '레아': 'Leia',
  '츄바카': 'Chewbacca',
  '오비완': 'Obi-Wan',
  '오비완케노비': 'Obi-Wan Kenobi',
  '레이': 'Rey',
  '카일로렌': 'Kylo Ren',
  '스톰트루퍼': 'Stormtrooper',
  '클론트루퍼': 'Clone Trooper',
  '밀레니엄팔콘': 'Millennium Falcon',
  '타이파이터': 'TIE Fighter',
  '엑스윙': 'X-Wing',
  '데스스타': 'Death Star',
  '스타데스트로이어': 'Star Destroyer',
  '해리포터': 'Harry Potter',
  '호빗': 'Hobbit',
  '반지의제왕': 'Lord of the Rings',
  '인디아나존스': 'Indiana Jones',
  '쥬라기월드': 'Jurassic World',
  '쥬라기공원': 'Jurassic Park',
  '아바타': 'Avatar',
  '스트레인저씽스': 'Stranger Things',
  '디즈니': 'Disney',
  '디즈니프린세스': 'Disney Princess',
  '미키마우스': 'Mickey Mouse',
  '미니마우스': 'Minnie Mouse',
  '엘사': 'Elsa',
  '안나': 'Anna',
  '라푼젤': 'Rapunzel',
  '인어공주': 'Little Mermaid',
  '알라딘': 'Aladdin',
  '라이온킹': 'Lion King',
  '겨울왕국': 'Frozen',
  '토이스토리': 'Toy Story',
  '카': 'Cars',
  '슈퍼마리오': 'Super Mario',
  '마리오': 'Mario',
  '루이지': 'Luigi',
  '스피드챔피언': 'Speed Champions',
  '포르쉐': 'Porsche',
  '페라리': 'Ferrari',
  '람보르기니': 'Lamborghini',
  '부가티': 'Bugatti',
  '맥라렌': 'McLaren',
  '메르세데스': 'Mercedes',
  '미니쿠퍼': 'Mini Cooper',
  '포드': 'Ford',
  '머스탱': 'Mustang',
  '아우디': 'Audi',
  '도요타': 'Toyota',
  '보태니컬': 'Botanical',
  '식물': 'Botanical',
  '꽃': 'Flower',
  '꽃다발': 'Flower Bouquet',
  '분재': 'Bonsai',
  '난초': 'Orchid',
  '장미': 'Roses',
  '해바라기': 'Sunflowers',
  '튤립': 'Tulips',
  '수선화': 'Daffodils',
  '새': 'Bird',
  '나비': 'Butterfly',
  '나사': 'NASA',
  '아폴로': 'Apollo',
  '새턴': 'Saturn V',
  '우주왕복선': 'Space Shuttle',
  '우주정거장': 'Space Station',
  '국제우주정거장': 'International Space Station',
  '로버': 'Rover',
  '잠수함': 'Submarine',
  '보트': 'Boat',
  '요트': 'Yacht',
  '등대': 'Lighthouse',
  '캠핑카': 'Camper Van',
  '산타': 'Santa',
  '크리스마스': 'Christmas',
  '크리스마스트리': 'Christmas Tree',
  '할로윈': 'Halloween',
  '핼러윈': 'Halloween',
  '이스터': 'Easter',
  '부활절': 'Easter',
  '동물': 'Animal',
  '펭귄': 'Penguin',
  '사자': 'Lion',
  '호랑이': 'Tiger',
  '곰': 'Bear',
  '판다': 'Panda',
  '짱구': 'Crayon Shin-chan',
  '포케몬': 'Pokemon',
  '지브리': 'Ghibli',
  '나루토': 'Naruto',
  '드래곤볼': 'Dragon Ball',
  '트리': 'Tree',
  '파이터': 'Fighter',
  '데스트로이어': 'Destroyer',
  '스카이워커': 'Skywalker',
  '포터': 'Potter',
  '베이더': 'Vader',
  '트루퍼': 'Trooper',
  '마우스': 'Mouse',
  '스토리': 'Story',
  '챔피언': 'Champions',
  '쿠퍼': 'Cooper',
  '아메리카': 'America',
  '위도우': 'Widow',
  '팬서': 'Panther',
  '스트레인지': 'Strange',
  '건틀렛': 'Gauntlet',
  '우먼': 'Woman',
  '요다': 'Yoda',
  '렌': 'Ren',
  '팔콘': 'Falcon',
  '윙': 'Wing',
  '파크': 'Park',
  '월드': 'World',
  '씽스': 'Things',
  '킹': 'King',
  '마리오': 'Mario',
  // ============================================================================
  // ===== Expanded Korean nicknames (added 2026-04-07 batch 2) =====
  // Goal: typing partial Korean names like "아캄" should reach 76300 etc.
  // ============================================================================
  // DC / Batman villains and locations
  '아캄': 'Arkham',
  '아캄어사일럼': 'Arkham Asylum',
  '아캄정신병원': 'Arkham Asylum',
  '고담': 'Gotham',
  '고담시티': 'Gotham City',
  '배트케이브': 'Batcave',
  '배트동굴': 'Batcave',
  '배트윙': 'Batwing',
  '배트보트': 'Batboat',
  '배트포드': 'Batpod',
  '리들러': 'Riddler',
  '투페이스': 'Two-Face',
  '베인': 'Bane',
  '캣우먼': 'Catwoman',
  '할리퀸': 'Harley Quinn',
  '할리': 'Harley',
  '미스터프리즈': 'Mr. Freeze',
  '스케어크로우': 'Scarecrow',
  '포이즌아이비': 'Poison Ivy',
  '펭귄맨': 'Penguin',
  '나이트윙': 'Nightwing',
  '로빈': 'Robin',
  '배트걸': 'Batgirl',
  '레드후드': 'Red Hood',
  '데스스트로크': 'Deathstroke',
  '렉스루터': 'Lex Luthor',
  '저스티스리그': 'Justice League',
  '사이보그': 'Cyborg',
  '그린랜턴': 'Green Lantern',
  // Marvel - more characters
  '디드풀': 'Deadpool',
  '데드풀': 'Deadpool',
  '울버린': 'Wolverine',
  '엑스맨': 'X-Men',
  '데어데블': 'Daredevil',
  '베놈': 'Venom',
  '카니지': 'Carnage',
  '그루트': 'Groot',
  '로켓': 'Rocket',
  '스타로드': 'Star-Lord',
  '드랙스': 'Drax',
  '가모라': 'Gamora',
  '닉퓨리': 'Nick Fury',
  '캡틴마블': 'Captain Marvel',
  '미즈마블': 'Ms. Marvel',
  '스파이더그웬': 'Spider-Gwen',
  '마일즈모랄레스': 'Miles Morales',
  '그린고블린': 'Green Goblin',
  '닥옥': 'Doctor Octopus',
  '닥터옥토퍼스': 'Doctor Octopus',
  '미스테리오': 'Mysterio',
  '샌드맨': 'Sandman',
  '쇼커': 'Shocker',
  '울트론': 'Ultron',
  '비전': 'Vision',
  '스칼렛위치': 'Scarlet Witch',
  '스칼렛': 'Scarlet Witch',
  '폴콘': 'Falcon',
  '윈터솔져': 'Winter Soldier',
  '벅키': 'Bucky',
  '쉴드': 'S.H.I.E.L.D.',
  '와칸다': 'Wakanda',
  '아스가르드': 'Asgard',
  '샹치': 'Shang-Chi',
  '문나이트': 'Moon Knight',
  '이터널스': 'Eternals',
  '슈퍼히어로': 'Super Heroes',
  // Star Wars - more characters and locations
  '보바펫': 'Boba Fett',
  '장고펫': 'Jango Fett',
  '핀': 'Finn',
  '포다메론': 'Poe Dameron',
  '시스': 'Sith',
  '제다이': 'Jedi',
  '리퍼블릭': 'Republic',
  '그리버스': 'Grievous',
  '둑쿠': 'Dooku',
  '두쿠': 'Dooku',
  '카운트두쿠': 'Count Dooku',
  '루크': 'Luke',
  '한': 'Han',
  '레이아': 'Leia',
  '패드미': 'Padme',
  '아미달라': 'Amidala',
  '메이스윈두': 'Mace Windu',
  '콰이곤진': 'Qui-Gon Jinn',
  '아소카': 'Ahsoka',
  '캡틴렉스': 'Captain Rex',
  '레이저크레스트': 'Razor Crest',
  '엔도르': 'Endor',
  '타투인': 'Tatooine',
  '나부': 'Naboo',
  '코러산트': 'Coruscant',
  '에이티에이티': 'AT-AT',
  '에이티에스티': 'AT-ST',
  '와이윙': 'Y-Wing',
  '에이윙': 'A-Wing',
  '비윙': 'B-Wing',
  '베나토르': 'Venator',
  '슬레이브': 'Slave I',
  // Harry Potter - more characters and locations
  '호그와트': 'Hogwarts',
  '호그스미드': 'Hogsmeade',
  '다이애건앨리': 'Diagon Alley',
  '다이애곤앨리': 'Diagon Alley',
  '아즈카반': 'Azkaban',
  '헤르미온느': 'Hermione',
  '론': 'Ron',
  '덤블도어': 'Dumbledore',
  '스네이프': 'Snape',
  '볼드모트': 'Voldemort',
  '해그리드': 'Hagrid',
  '말포이': 'Malfoy',
  '드레이코': 'Draco',
  '루나': 'Luna',
  '네빌': 'Neville',
  '시리우스': 'Sirius',
  '루핀': 'Lupin',
  '벅비크': 'Buckbeak',
  '도비': 'Dobby',
  '그리핀도르': 'Gryffindor',
  '슬리데린': 'Slytherin',
  '후플푸프': 'Hufflepuff',
  '래븐클로': 'Ravenclaw',
  '신비한동물사전': 'Fantastic Beasts',
  '뉴트': 'Newt Scamander',
  // Disney / Pixar - additional
  '인사이드아웃': 'Inside Out',
  '코코': 'Coco',
  '모아나': 'Moana',
  '라야': 'Raya',
  '엔칸토': 'Encanto',
  '주토피아': 'Zootopia',
  '빅히어로': 'Big Hero',
  '미녀와야수': 'Beauty and the Beast',
  '신데렐라': 'Cinderella',
  '백설공주': 'Snow White',
  '잠자는숲속의공주': 'Sleeping Beauty',
  '몬스터주식회사': 'Monsters Inc',
  '니모를찾아서': 'Finding Nemo',
  '도리': 'Dory',
  '인크레더블': 'Incredibles',
  '라따뚜이': 'Ratatouille',
  '월E': 'WALL-E',
  '월이': 'WALL-E',
  '업': 'Up',
  '카2': 'Cars',
  '소울': 'Soul',
  '루카': 'Luca',
  // Other IPs / anime / games
  '닌자거북이': 'Ninja Turtles',
  '거북이': 'Turtles',
  '트랜스포머': 'Transformers',
  '소닉': 'Sonic',
  '듄': 'Dune',
  '아바타라스트에어벤더': 'Avatar Last Airbender',
  '베트맨': 'Batman',
  '스폰지밥': 'SpongeBob',
  '심슨': 'Simpsons',
  '심슨가족': 'Simpsons',
  // City themes / vehicles - additional
  '우주센터': 'Space Center',
  '우주비행사': 'Astronaut',
  '잠수정': 'Submarine',
  '컨테이너': 'Container',
  '컨테이너선': 'Container Ship',
  '구급차': 'Ambulance',
  '경비행기': 'Aircraft',
  '전투기': 'Fighter Jet',
  '탱크': 'Tank',
  '불도저': 'Bulldozer',
  '굴착기': 'Excavator',
  '크레인': 'Crane',
  '레이싱카': 'Race Car',
  '경주차': 'Race Car',
  '카트': 'Kart',
  '캠프카': 'Camper Van',
  // Castle / medieval extras
  '기사': 'Knight',
  '드래곤': 'Dragon',
  '용': 'Dragon',
  '와이번': 'Wyvern',
  '바이킹': 'Viking',
  '롱쉽': 'Longship',
  '타워': 'Tower',
  '왕좌': 'Throne',
  '대장간': 'Blacksmith',
  '풍차': 'Windmill',
  '시골집': 'Cottage',
  '오두막': 'Cabin',
  // LOTR / fantasy
  '간달프': 'Gandalf',
  '프로도': 'Frodo',
  '아라곤': 'Aragorn',
  '레골라스': 'Legolas',
  '김리': 'Gimli',
  '사우론': 'Sauron',
  '리븐델': 'Rivendell',
  '모리아': 'Moria',
  '미나스티리스': 'Minas Tirith',
  '바라드두르': 'Barad-dur',
  // Botanical / nature extras
  '벚꽃': 'Cherry Blossom',
  '단풍': 'Maple',
  '대나무': 'Bamboo',
  '선인장': 'Cactus',
  '다육': 'Succulent',
  '버섯': 'Mushroom',
  // Misc popular sets
  '아이콘': 'Icons',
  '아이콘즈': 'Icons',
  '엘프': 'Elves',
  '바이오니클': 'Bionicle',
  '히어로팩토리': 'Hero Factory',
  '엑소포스': 'Exo-Force',
  '닌자': 'Ninja',
  '와일드웨스트': 'Wild West',
  '서부': 'Western',
  '카우보이': 'Cowboy',
  '인디언': 'Indian',
  // Single-syllable ambiguous (kept short, may match many)
  '캐슬': 'Castle',
  '나이트': 'Knight',
  '레이서': 'Racers',
  '레이싱': 'Racing',
  '시티': 'City',
  '월드시티': 'World City',
};

// ============================================================================
// IP / Franchise Multi-Keyword Expansion (added 2026-04)
// ----------------------------------------------------------------------------
// Rebrickable's /sets/?search=... only matches set NAMES (not theme names),
// so umbrella keywords like "Marvel" return zero results because no set name
// contains the word "Marvel". For these umbrella franchise keywords we instead
// fan out into multiple parallel searches against terms that DO appear in set
// names (Spider-Man, Iron Man, Avengers, Hulk, ...) and merge the results.
// Both Korean (raw) and English (translated) keys are accepted.
// ============================================================================
var IP_SEARCH_MAP = {
  // Marvel umbrella
  '마블': ['Spider-Man', 'Iron Man', 'Avengers', 'Hulk', 'Captain America', 'Thor', 'Black Panther', 'Doctor Strange', 'Spidey', 'Guardians', 'Ant-Man'],
  'marvel': ['Spider-Man', 'Iron Man', 'Avengers', 'Hulk', 'Captain America', 'Thor', 'Black Panther', 'Doctor Strange', 'Spidey', 'Guardians', 'Ant-Man'],
  '어벤져스': ['Avengers', 'Iron Man', 'Hulk', 'Thor', 'Captain America', 'Black Widow'],
  '어벤저스': ['Avengers', 'Iron Man', 'Hulk', 'Thor', 'Captain America', 'Black Widow'],
  'avengers': ['Avengers', 'Iron Man', 'Hulk', 'Thor', 'Captain America', 'Black Widow'],
  '아이언맨': ['Iron Man', 'Hulkbuster', 'Stark'],
  'iron man': ['Iron Man', 'Hulkbuster', 'Stark'],
  '헐크': ['Hulk', 'Hulkbuster'],
  'hulk': ['Hulk', 'Hulkbuster'],
  '스파이더맨': ['Spider-Man', 'Spidey'],
  'spider-man': ['Spider-Man', 'Spidey'],
  'spiderman': ['Spider-Man', 'Spidey'],
  '캡틴아메리카': ['Captain America'],
  '캡틴 아메리카': ['Captain America'],
  '토르': ['Thor'],
  'thor': ['Thor'],
  '블랙위도우': ['Black Widow'],
  '블랙 위도우': ['Black Widow'],
  '블랙팬서': ['Black Panther'],
  '블랙 팬서': ['Black Panther'],
  '닥터스트레인지': ['Doctor Strange'],
  '닥터 스트레인지': ['Doctor Strange'],
  '가디언즈': ['Guardians', 'Star-Lord'],
  '가디언즈오브갤럭시': ['Guardians', 'Star-Lord'],
  '앤트맨': ['Ant-Man'],
  '엑스맨': ['X-Men', 'Wolverine', 'Cyclops', 'Storm', 'Magneto'],
  'x-men': ['X-Men', 'Wolverine', 'Cyclops', 'Storm', 'Magneto'],
  // DC umbrella
  '디씨': ['Batman', 'Superman', 'Wonder Woman', 'Joker', 'Aquaman', 'Justice League', 'Arkham'],
  'dc': ['Batman', 'Superman', 'Wonder Woman', 'Joker', 'Aquaman', 'Justice League', 'Arkham'],
  '저스티스리그': ['Justice League'],
  '슈퍼맨': ['Superman'],
  '원더우먼': ['Wonder Woman'],
  '원더 우먼': ['Wonder Woman'],
  '아쿠아맨': ['Aquaman'],
  '플래시': ['Flash'],
  '조커': ['Joker'],
  '배트맨': ['Batman', 'Batmobile', 'Batcave', 'Arkham', 'Gotham'],
  'batman': ['Batman', 'Batmobile', 'Batcave', 'Arkham', 'Gotham'],
  // Star Wars umbrella
  '스타워즈': ['Star Wars', 'Millennium Falcon', 'X-Wing', 'TIE Fighter', 'AT-AT', 'Death Star', 'Mandalorian', 'Clone'],
  '스타 워즈': ['Star Wars', 'Millennium Falcon', 'X-Wing', 'TIE Fighter', 'AT-AT', 'Death Star', 'Mandalorian'],
  'star wars': ['Star Wars', 'Millennium Falcon', 'X-Wing', 'TIE Fighter', 'AT-AT', 'Death Star', 'Mandalorian'],
  '만달로리안': ['Mandalorian', 'Razor Crest', 'Grogu'],
  '클론': ['Clone Trooper', 'Clone Wars'],
  // Pirates / Pirates of Barracuda Bay
  '바라쿠다': ['Barracuda', 'Barracuda Bay', 'Pirates of Barracuda Bay'],
  'barracuda': ['Barracuda', 'Barracuda Bay', 'Pirates of Barracuda Bay'],
  // Harry Potter umbrella
  '해리포터': ['Harry Potter', 'Hogwarts', 'Diagon Alley', 'Hogsmeade'],
  '해리 포터': ['Harry Potter', 'Hogwarts', 'Diagon Alley', 'Hogsmeade'],
  'harry potter': ['Harry Potter', 'Hogwarts', 'Diagon Alley', 'Hogsmeade'],
  // Disney
  '디즈니': ['Disney', 'Mickey', 'Minnie', 'Frozen', 'Lion King', 'Toy Story'],
  'disney': ['Disney', 'Mickey', 'Minnie', 'Frozen', 'Lion King', 'Toy Story'],
  '겨울왕국': ['Frozen', 'Elsa', 'Anna'],
  'frozen': ['Frozen', 'Elsa', 'Anna'],
  // Other movies / IPs
  '쥬라기월드': ['Jurassic World', 'T. rex', 'Velociraptor'],
  '쥬라기 월드': ['Jurassic World', 'T. rex', 'Velociraptor'],
  'jurassic world': ['Jurassic World', 'T. rex', 'Velociraptor'],
  '쥬라기공원': ['Jurassic Park'],
  '쥬라기 공원': ['Jurassic Park'],
  '인디아나존스': ['Indiana Jones'],
  '인디아나 존스': ['Indiana Jones'],
  '슈퍼마리오': ['Super Mario', 'Mario', 'Luigi', 'Bowser', 'Peach'],
  '슈퍼 마리오': ['Super Mario', 'Mario', 'Luigi', 'Bowser', 'Peach'],
  'super mario': ['Super Mario', 'Mario', 'Luigi', 'Bowser', 'Peach'],
  '미니언즈': ['Minions'],
  'minions': ['Minions'],
  '반지의제왕': ['Lord of the Rings', 'Hobbit'],
  '반지의 제왕': ['Lord of the Rings', 'Hobbit'],
  '레고무비': ['LEGO Movie'],
  '레고 무비': ['LEGO Movie'],
  // Speed Champions / cars umbrella
  '스피드챔피언': ['Speed Champions', 'Porsche', 'Ferrari', 'Lamborghini', 'McLaren', 'Bugatti'],
  '스피드 챔피언': ['Speed Champions', 'Porsche', 'Ferrari', 'Lamborghini', 'McLaren', 'Bugatti'],
};

// Returns an array of English search terms for an umbrella IP/franchise query,
// or null if the query is not a known umbrella keyword. Accepts both raw
// Korean and pre-translated English (case-insensitive).
function getIpSearchTerms(query) {
  if (!query) return null;
  var trimmed = String(query).trim();
  if (!trimmed) return null;
  if (IP_SEARCH_MAP[trimmed]) return IP_SEARCH_MAP[trimmed];
  var lower = trimmed.toLowerCase();
  if (IP_SEARCH_MAP[lower]) return IP_SEARCH_MAP[lower];
  return null;
}

function translateSearchQuery(q) {
  if (!q) return '';

  var trimmed = q.trim();

  // 1. Check SET_NUM_MAP exact match first (nickname -> set number)
  if (SET_NUM_MAP[trimmed]) {
    return SET_NUM_MAP[trimmed];
  }

  // 2. Check PHRASE_MAP (exact phrase in query)
  for (var i = 0; i < PHRASE_MAP.length; i++) {
    if (trimmed.indexOf(PHRASE_MAP[i][0]) !== -1) {
      return PHRASE_MAP[i][1];
    }
  }

  // 3. Word-based translation (WORD_MAP) - check BEFORE prefix matching
  var words = trimmed.split(' ');
  var newWords = [];
  var anyTranslated = false;
  for (var j = 0; j < words.length; j++) {
    var word = words[j];
    if (WORD_MAP[word]) {
      newWords.push(WORD_MAP[word]);
      anyTranslated = true;
    } else {
      newWords.push(word);
    }
  }
  if (anyTranslated) {
    return newWords.join(' ');
  }

  // 4. Partial word match from WORD_MAP
  var bestWord = null;
  var bestWordLen = 0;
  var keys = Object.keys(WORD_MAP);
  for (var w = 0; w < keys.length; w++) {
    var wko = keys[w];
    if (wko.indexOf(trimmed) === 0 && trimmed.length >= 2 && wko.length > bestWordLen) {
      bestWord = WORD_MAP[wko];
      bestWordLen = wko.length;
    }
    if (trimmed.indexOf(wko) === 0 && wko.length > bestWordLen) {
      bestWord = WORD_MAP[wko];
      bestWordLen = wko.length;
    }
  }
  if (bestWord) {
    return bestWord;
  }

  // 5. SET_NUM_MAP prefix matching (LAST, strict: query must cover >= 60% of key)
  var setKeys = Object.keys(SET_NUM_MAP);
  for (var sk = 0; sk < setKeys.length; sk++) {
    if (setKeys[sk].indexOf(trimmed) === 0 && trimmed.length >= 2 && trimmed.length >= setKeys[sk].length * 0.6) {
      return SET_NUM_MAP[setKeys[sk]];
    }
  }

  return trimmed;
}

export { translateSearchQuery, SET_NUM_MAP, getIpSearchTerms };
