// Korean to English LEGO search keyword dictionary
// Sorted by priority: exact phrases first, then single words

var SET_NUM_MAP = {
  '용마성': '6082',
  '비룡성': '6086',
  '흡룡성': '6085',
  '박쥐성': '6097',
  '유령성': '6081',
  '사자성': '6080',
  '왕의성': '6080',
  '숙의성': '6077',
  '숨의성': '6077',
  '숨속성': '6077',
  '숨속요새': '6077',
  '흡기사성': '6086',
  '마차성': '6042',
  '마법사성': '6048',
  '마법성': '6048',
  '독수리성': '6098',
  '사자기사성': '10305',
  '황소성': '375',
  '노란성': '375',
  '블랙펄': '10365',
  '블랙 펄': '10365',
  '해적선': '10365',
  '잭스패로우': '10365',
  '잭 스패로우': '10365',
  '쳨리비안의해적': '10365',
  '쳨리비안 해적': '10365',
  '타이타닉': '10294',
  '콜로세움': '10276',
  '에펄탑': '10307',
  '나무집': '21318',
  '트리하우스': '21318',
  '중세대장간': '21325',
  '중세 대장간': '21325',
  '그랜드피아노': '21323',
  '지구본': '21332',
  '타자기': '21327',
  '콘코드': '10318',
  '밀레니엄팜콘': '75192',
  '밀레니엄 팜콘': '75192',
  '디즈니성': '71040',
  '디즈니 성': '71040',
  '디즈니커슬': '71040',
  // ===== Modular Buildings =====
  '카페코너': '10182',
  '카페 코너': '10182',
  '그린그로서': '10185',
  '그린 그로서': '10185',
  '야채가게': '10185',
  '마켓스트리트': '10190',
  '마켓 스트리트': '10190',
  '소방대': '10197',
  '국민모듈러': '10197',
  '대형백화점': '10211',
  '그랜드엠포리엄': '10211',
  '그랜드 엠포리엄': '10211',
  '백화점': '10211',
  '펫샵': '10218',
  '펫 샵': '10218',
  '애완동물샵': '10218',
  '애완동물 가게': '10218',
  '타운홀': '10224',
  '타운 홀': '10224',
  '시청': '10224',
  '팔레스시네마': '10232',
  '팔레스 시네마': '10232',
  '파리지앵레스토랑': '10243',
  '파리지앵 레스토랑': '10243',
  '파리 레스토랑': '10243',
  '파리의 레스토랑': '10243',
  '탐정사무소': '10246',
  '탐정 사무소': '10246',
  '브릭뭅크': '10251',
  '브릭 뭅크': '10251',
  '브릭은행': '10251',
  '어셈블리스퀘어': '10255',
  '어셈블리 스퀘어': '10255',
  '다운타운다이너': '10260',
  '다운타운 다이너': '10260',
  '코너가라지': '10264',
  '코너 가라지': '10264',
  '코너정비소': '10264',
  '코너 정비소': '10264',
  '서점': '10270',
  '북샵': '10270',
  '북 샵': '10270',
  '모듈러경찰서': '10278',
  '모듈러 경찰서': '10278',
  '부티크호텔': '10297',
  '부티크 호텔': '10297',
  '재즈클럽': '10312',
  '재즈 클럽': '10312',
  '자연사박물관': '10326',
  '자연사 박물관': '10326',
  '튜더코너': '10350',
  '튜더 코너': '10350',
  '쇼핑스트리트': '11371',
  '쇼핑 스트리트': '11371',
};

var PHRASE_MAP = [
  // ===== Harry Potter =====
  ['다이애랩건 알리', 'Diagon Alley'],
  ['다이애랩건알리', 'Diagon Alley'],
  ['해리포터', 'Harry Potter'],
  ['해리 포터', 'Harry Potter'],
  ['호그와트 익스프레스', 'Hogwarts Express'],
  ['호그와트 성', 'Hogwarts Castle'],
  ['호그와트성', 'Hogwarts Castle'],
  ['호그와트리링', 'Hogsmeade'],
  ['호그마리', 'Hogsmeade'],
  ['따른내냨', 'Diagon Alley'],
  ['내냨거리', 'Diagon Alley'],
  ['호그낸른', 'Hogsmeade'],

  // ===== Pirates =====
  ['비나칭', 'Pirates'],
  ['비나칭내외', 'Pirates'],
  ['블랙 펄', 'Black Pearl'],
  ['쳨리비안의 해적', 'Pirates of the Caribbean'],
  ['쳨리비안 해적', 'Pirates of the Caribbean'],
  ['잭스패로우', 'Jack Sparrow'],
  ['잭 스패로우', 'Jack Sparrow'],
  ['쳪턴 잭 스패로우', 'Captain Jack Sparrow'],

  // ===== Modular Buildings =====
  ['카페코너', 'Cafe Corner'],
  ['카페 코너', 'Cafe Corner'],
  ['그린그로서', 'Green Grocer'],
  ['그린 그로서', 'Green Grocer'],
  ['마켓스트리트', 'Market Street'],
  ['마켓 스트리트', 'Market Street'],
  ['소방대', 'Fire Brigade'],
  ['국민모듈러', 'Fire Brigade'],
  ['대형백화점', 'Grand Emporium'],
  ['그랜드엠포리엄', 'Grand Emporium'],
  ['그랜드 엠포리엄', 'Grand Emporium'],
  ['펫샵', 'Pet Shop'],
  ['펫 샵', 'Pet Shop'],
  ['애완동물샵', 'Pet Shop'],
  ['애완동물 가게', 'Pet Shop'],
  ['팔레스시네마', 'Palace Cinema'],
  ['팔레스 시네마', 'Palace Cinema'],
  ['파리지앵레스토랑', 'Parisian Restaurant'],
  ['파리지앵 레스토랑', 'Parisian Restaurant'],
  ['파리 레스토랑', 'Parisian Restaurant'],
  ['파리의 레스토랑', 'Parisian Restaurant'],
  ['탐정사무소', "Detective's Office"],
  ['탐정 사무소', "Detective's Office"],
  ['브릭뭅크', 'Brick Bank'],
  ['브릭 뭅크', 'Brick Bank'],
  ['브릭은행', 'Brick Bank'],
  ['코너정비소', 'Corner Garage'],
  ['코너 정비소', 'Corner Garage'],
  ['북샵', 'Bookshop'],
  ['북 샵', 'Bookshop'],
  ['모듈러경찰서', 'Police Station'],
  ['모듈러 경찰서', 'Police Station'],
  ['튜더코너', 'Tudor Corner'],
  ['튜더 코너', 'Tudor Corner'],
  ['쇼핑스트리트', 'Shopping Street'],
  ['쇼핑 스트리트', 'Shopping Street'],

  // ===== Technic vehicles =====
  ['뎘이던동차', 'Motorized RC Car'],
  ['뎘이던 동차', 'Motorized RC Car'],
  ['거대온뫐네더', 'Geared RC Car'],
  ['거대 온뫐네더', 'Geared RC Car'],

  // ===== Multi-word phrases (added 2026-04) =====
  ['캡틴 아메리카', 'Captain America'],
  ['블랙 위도우', 'Black Widow'],
  ['블랙 팬서', 'Black Panther'],
  ['닥터 스트레인지', 'Doctor Strange'],
  ['인피니티 건틀렛', 'Infinity Gauntlet'],
  ['원더 우먼', 'Wonder Woman'],
  ['베이비 요다', 'Grogu'],
  ['다스 베이더', 'Darth Vader'],
  ['루크 스카이워커', 'Luke Skywalker'],
  ['한 솔로', 'Han Solo'],
  ['카일로 렌', 'Kylo Ren'],
  ['클론 트루퍼', 'Clone Trooper'],
  ['밀레니엄 팔콘', 'Millennium Falcon'],
  ['타이 파이터', 'TIE Fighter'],
  ['엑스 윙', 'X-Wing'],
  ['데스 스타', 'Death Star'],
  ['스타 데스트로이어', 'Star Destroyer'],
  ['해리 포터', 'Harry Potter'],
  ['반지의 제왕', 'Lord of the Rings'],
  ['인디아나 존스', 'Indiana Jones'],
  ['쥬라기 월드', 'Jurassic World'],
  ['쥬라기 공원', 'Jurassic Park'],
  ['스트레인저 씽스', 'Stranger Things'],
  ['미키 마우스', 'Mickey Mouse'],
  ['라이온 킹', 'Lion King'],
  ['토이 스토리', 'Toy Story'],
  ['슈퍼 마리오', 'Super Mario'],
  ['스피드 챔피언', 'Speed Champions'],
  ['미니 쿠퍼', 'Mini Cooper'],
  ['캠핑 카', 'Camper Van'],
  ['크리스마스 트리', 'Christmas Tree'],
];

var WORD_MAP = {
  '다이애랩건': 'Diagon Alley',
  '나무': 'Tree',
  '모듈러': 'Modular',
  '스타워즈': 'Star Wars',
  '스타': 'Star',
  '마법': 'Magic',
  '성': 'Castle',
  '해적': 'Pirate',
  '우주': 'Space',
  '도시': 'City',
  '기차': 'Train',
  '비행기': 'Airplane',
  '로봇': 'Robot',
  '닌자고': 'Ninjago',
  '테크닉': 'Technic',
  '듀플로': 'Duplo',
  '프렌즈': 'Friends',
  '배트맨': 'Batman',
  '슈퍼히어로': 'Super Hero',
  '마인크래프트': 'Minecraft',
  '마인 크래프트': 'Minecraft',
  '아이디어': 'Ideas',
  '크리에이터': 'Creator',
  '크리에이터 전문가': 'Creator Expert',
  '아키텍처': 'Architecture',
  // ===== Common Korean search terms =====
  '경찰서': 'Police Station',
  '경찰': 'Police',
  '소방서': 'Fire Station',
  '소방': 'Fire',
  '병원': 'Hospital',
  '학교': 'School',
  '공항': 'Airport',
  '항구': 'Harbor',
  '항구도시': 'Harbor City',
  '배': 'Ship',
  '배배': 'Ship',
  '비행': 'Flight',
  '소방차': 'Fire Truck',
  '경찰차': 'Police Car',
  '자동차': 'Car',
  '트럭': 'Truck',
  '버스': 'Bus',
  '헬리콥터': 'Helicopter',
  '오토바이': 'Motorcycle',
  '농장': 'Farm',
  '정글': 'Jungle',
  '탐험': 'Exploration',
  '우주선': 'Spaceship',
  '로켓': 'Rocket',
  '달기지': 'Moon Base',
  '화성': 'Mars',
  '공룡': 'Dinosaur',
  '연립': 'United',
  '박물관': 'Museum',
  '도서관': 'Library',
  '식당': 'Restaurant',
  '카페': 'Cafe',
  '호텔': 'Hotel',
  '영화관': 'Cinema',
  '가게': 'Shop',
  '상점': 'Store',
  '시장': 'Market',
  '레스토랑': 'Restaurant',
  '은행': 'Bank',
  '우체국': 'Post Office',
  '주유소': 'Gas Station',
  '정비소': 'Garage',
  // ===== Marvel / DC / Star Wars / Movies / IPs / Brands / Botanical (added 2026-04) =====
  '마블': 'Marvel',
  '어벤져스': 'Avengers',
  '어벤저스': 'Avengers',
  '스파이더맨': 'Spider-Man',
  '아이언맨': 'Iron Man',
  '캡틴아메리카': 'Captain America',
  '토르': 'Thor',
  '헐크': 'Hulk',
  '블랙위도우': 'Black Widow',
  '블랙팬서': 'Black Panther',
  '가디언즈': 'Guardians of the Galaxy',
  '가디언즈오브갤럭시': 'Guardians of the Galaxy',
  '닥터스트레인지': 'Doctor Strange',
  '앤트맨': 'Ant-Man',
  '완다': 'Wanda',
  '로키': 'Loki',
  '타노스': 'Thanos',
  '인피니티건틀렛': 'Infinity Gauntlet',
  '헐크버스터': 'Hulkbuster',
  '디씨': 'DC',
  '슈퍼맨': 'Superman',
  '원더우먼': 'Wonder Woman',
  '아쿠아맨': 'Aquaman',
  '플래시': 'Flash',
  '조커': 'Joker',
  '배트모빌': 'Batmobile',
  '만달로리안': 'Mandalorian',
  '만달로어': 'Mandalorian',
  '베이비요다': 'Grogu',
  '그로구': 'Grogu',
  '다스베이더': 'Darth Vader',
  '요다': 'Yoda',
  '루크스카이워커': 'Luke Skywalker',
  '한솔로': 'Han Solo',
  '레아': 'Leia',
  '츄바카': 'Chewbacca',
  '오비완': 'Obi-Wan',
  '오비완케노비': 'Obi-Wan Kenobi',
  '레이': 'Rey',
  '카일로렌': 'Kylo Ren',
  '스톰트루퍼': 'Stormtrooper',
  '클론트루퍼': 'Clone Trooper',
  '밀레니엄팔콘': 'Millennium Falcon',
  '타이파이터': 'TIE Fighter',
  '엑스윙': 'X-Wing',
  '데스스타': 'Death Star',
  '스타데스트로이어': 'Star Destroyer',
  '해리포터': 'Harry Potter',
  '호빗': 'Hobbit',
  '반지의제왕': 'Lord of the Rings',
  '인디아나존스': 'Indiana Jones',
  '쥬라기월드': 'Jurassic World',
  '쥬라기공원': 'Jurassic Park',
  '아바타': 'Avatar',
  '스트레인저씽스': 'Stranger Things',
  '디즈니': 'Disney',
  '디즈니프린세스': 'Disney Princess',
  '미키마우스': 'Mickey Mouse',
  '미니마우스': 'Minnie Mouse',
  '엘사': 'Elsa',
  '안나': 'Anna',
  '라푼젤': 'Rapunzel',
  '인어공주': 'Little Mermaid',
  '알라딘': 'Aladdin',
  '라이온킹': 'Lion King',
  '겨울왕국': 'Frozen',
  '토이스토리': 'Toy Story',
  '카': 'Cars',
  '슈퍼마리오': 'Super Mario',
  '마리오': 'Mario',
  '루이지': 'Luigi',
  '스피드챔피언': 'Speed Champions',
  '포르쉐': 'Porsche',
  '페라리': 'Ferrari',
  '람보르기니': 'Lamborghini',
  '부가티': 'Bugatti',
  '맥라렌': 'McLaren',
  '메르세데스': 'Mercedes',
  '미니쿠퍼': 'Mini Cooper',
  '포드': 'Ford',
  '머스탱': 'Mustang',
  '아우디': 'Audi',
  '도요타': 'Toyota',
  '보태니컬': 'Botanical',
  '식물': 'Botanical',
  '꽃': 'Flower',
  '꽃다발': 'Flower Bouquet',
  '분재': 'Bonsai',
  '난초': 'Orchid',
  '장미': 'Roses',
  '해바라기': 'Sunflowers',
  '튤립': 'Tulips',
  '수선화': 'Daffodils',
  '새': 'Bird',
  '나비': 'Butterfly',
  '나사': 'NASA',
  '아폴로': 'Apollo',
  '새턴': 'Saturn V',
  '우주왕복선': 'Space Shuttle',
  '우주정거장': 'Space Station',
  '국제우주정거장': 'International Space Station',
  '로버': 'Rover',
  '잠수함': 'Submarine',
  '보트': 'Boat',
  '요트': 'Yacht',
  '등대': 'Lighthouse',
  '캠핑카': 'Camper Van',
  '산타': 'Santa',
  '크리스마스': 'Christmas',
  '크리스마스트리': 'Christmas Tree',
  '할로윈': 'Halloween',
  '핼러윈': 'Halloween',
  '이스터': 'Easter',
  '부활절': 'Easter',
  '동물': 'Animal',
  '펭귄': 'Penguin',
  '사자': 'Lion',
  '호랑이': 'Tiger',
  '곰': 'Bear',
  '판다': 'Panda',
  '짱구': 'Crayon Shin-chan',
  '포케몬': 'Pokemon',
  '지브리': 'Ghibli',
  '나루토': 'Naruto',
  '드래곤볼': 'Dragon Ball',
  '트리': 'Tree',
  '파이터': 'Fighter',
  '데스트로이어': 'Destroyer',
  '스카이워커': 'Skywalker',
  '포터': 'Potter',
  '베이더': 'Vader',
  '트루퍼': 'Trooper',
  '마우스': 'Mouse',
  '스토리': 'Story',
  '챔피언': 'Champions',
  '쿠퍼': 'Cooper',
  '아메리카': 'America',
  '위도우': 'Widow',
  '팬서': 'Panther',
  '스트레인지': 'Strange',
  '건틀렛': 'Gauntlet',
  '우먼': 'Woman',
  '요다': 'Yoda',
  '렌': 'Ren',
  '팔콘': 'Falcon',
  '윙': 'Wing',
  '파크': 'Park',
  '월드': 'World',
  '씽스': 'Things',
  '킹': 'King',
  '마리오': 'Mario',
};

function translateSearchQuery(q) {
  if (!q) return '';

  var trimmed = q.trim();

  // 1. Check SET_NUM_MAP exact match first (nickname -> set number)
  if (SET_NUM_MAP[trimmed]) {
    return SET_NUM_MAP[trimmed];
  }

  // 2. Check PHRASE_MAP (exact phrase in query)
  for (var i = 0; i < PHRASE_MAP.length; i++) {
    if (trimmed.indexOf(PHRASE_MAP[i][0]) !== -1) {
      return PHRASE_MAP[i][1];
    }
  }

  // 3. Word-based translation (WORD_MAP) - check BEFORE prefix matching
  var words = trimmed.split(' ');
  var newWords = [];
  var anyTranslated = false;
  for (var j = 0; j < words.length; j++) {
    var word = words[j];
    if (WORD_MAP[word]) {
      newWords.push(WORD_MAP[word]);
      anyTranslated = true;
    } else {
      newWords.push(word);
    }
  }
  if (anyTranslated) {
    return newWords.join(' ');
  }

  // 4. Partial word match from WORD_MAP
  var bestWord = null;
  var bestWordLen = 0;
  var keys = Object.keys(WORD_MAP);
  for (var w = 0; w < keys.length; w++) {
    var wko = keys[w];
    if (wko.indexOf(trimmed) === 0 && trimmed.length >= 2 && wko.length > bestWordLen) {
      bestWord = WORD_MAP[wko];
      bestWordLen = wko.length;
    }
    if (trimmed.indexOf(wko) === 0 && wko.length > bestWordLen) {
      bestWord = WORD_MAP[wko];
      bestWordLen = wko.length;
    }
  }
  if (bestWord) {
    return bestWord;
  }

  // 5. SET_NUM_MAP prefix matching (LAST, strict: query must cover >= 60% of key)
  var setKeys = Object.keys(SET_NUM_MAP);
  for (var sk = 0; sk < setKeys.length; sk++) {
    if (setKeys[sk].indexOf(trimmed) === 0 && trimmed.length >= 2 && trimmed.length >= setKeys[sk].length * 0.6) {
      return SET_NUM_MAP[setKeys[sk]];
    }
  }

  return trimmed;
}

export { translateSearchQuery, SET_NUM_MAP };
